apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goss
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: goss
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: goss
    interval: 10s
    path: /healthz
    honorLabels: true
