apiVersion: v1
kind: Endpoints
metadata:
  name: goss
  namespace: monitoring
  labels:
    app: goss
subsets:
  - addresses:
    - ip: 172.30.1.2
    ports:
      - name: goss
        port: 8080
        protocol: TCP