apiVersion: v1
kind: Service
metadata:
  name: goss
  namespace: monitoring
  labels:
    app: goss
spec:
  type: ExternalName
  externalName: 172.30.1.2
  clusterIP: ""
  ports:
  - name: goss
    port: 8080  
    protocol: TCP
    targetPort: 8080
